### ISSUE TITLE
Mistypes in README.MD

### ISSUE THREAD

**Issue by johnd0e** [Amm1rr/WebAI-to-API#10]
1. `http://128.0.0.1:8000`
   Perhaps should be `http://127.0.0.1:8000` or `http://localhost:8000`
2.
```
# Input:
_____

    {
      "session_id": "session-ID",
      "message": "Hi, Who are you?",
      "stream": True
    }
```
It is not clear whether it is python source or json.
(For json should br `"stream": true`)

**Comment by Amm1rr** [comment]
Readme and instructions have been updated to be more clear.
