### ISSUE TITLE
ChatGPT - Error 500 Undocumented 

### ISSUE THREAD

**Issue by myselfshravan** [Amm1rr/WebAI-to-API#19]
for chat gpt i am getting this error:
<p>Unable to load site</p>
</div>
<span class="explanation">
Please try again later. If you are using a VPN, try turning it off. Check the<a href="https://status.openai.com/" target="_new">status page</a> for information on outages.
</span>
and for claude i am getting this server response :
<html>
<body>

Code | Details
-- | --
500Undocumented | Error: Internal Server ErrorResponse bodyDownloadInternal Server Error

</body>
</html>

**Comment by baruahpranam** [comment]
Yes I am also getting the same problem.   Please try again later. If you are using a VPN, try turning it off.

**Comment by Amm1rr** [comment]
Is the issue still ongoing?

**Comment by baruahpranam** [comment]
Yes the Issue is still there. I have uninstalled it and again I reinstalled it but still it is showing problem for chat gpt. Please Solve it. It is happening from past 2 days.

**Comment by XenocodeRCE** [comment]
to add matter to this


```
Error: OpenAI: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>bypass.churchless.tech | 502: Bad gateway</title>
```

this might be due to this

**Comment by baruahpranam** [comment]
`
{
      "session_id": "",
      "message": "how many bones are there in a human",
      "stream": false
    }
`
`
Error: OpenAI: <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>


<title>bypass.churchless.tech | 502: Bad gateway</title>
`

**Comment by Cornatul** [comment]
@baruahpranam  I think you are beeing blocked by cloudflare 
https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=bypass.churchless.tech\

**Comment by baruahpranam** [comment]
I am very upset. Not working why I don't know. Earlier it was working fine. I tried all possible things that can be done but I am not able to resolve the issue. Actually I am not aware where the problem is occurring. No proper error logs I am getting.

**Comment by Amm1rr** [comment]
Hi guys,

The problem is that OpenAI uses Cloudflare to block requests without a browser. There is only one way to use the OpenAI website and that is to simulate a browser and get a session.

By the way, it will take some time to fix it. For now, I have decided to use other providers that are simpler and faster.

I will update the code soon with new providers instead of trying to simulate a browser for OpenAI access.
