### ISSUE TITLE
使用时出现bug

### ISSUE THREAD

**Issue by luoysuan** [Amm1rr/WebAI-to-API#22]
**在使用bard时配置参数没有**
![image](https://github.com/Amm1rr/WebAI-to-API/assets/51365362/b8c98bc3-4337-439a-99e3-1bf66a20819f)
![image](https://github.com/Amm1rr/WebAI-to-API/assets/51365362/364abd33-d6c9-4b55-ba19-00d9ebca5817)

**能否配置代理请求**

**Comment by Amm1rr** [comment]
Oops, that's a typo. Thank you for catching that. 

You should search for **__Secure-1PSIDCC__** instead of that.
