### ISSUE TITLE
v1/chat/completions error not found

### ISSUE THREAD

**Issue by PROFESSORLUXRY** [Amm1rr/WebAI-to-API#32]
Hello , i m used api adress ip adress/v1/chat/completions but i m see error not found
any ideas ? or this is adress not cupported ?
![Screenshot_1](https://github.com/Amm1rr/WebAI-to-API/assets/167172547/b3530c2a-ef34-43ee-b2e4-24cfe79381cf)

**Comment by Amm1rr** [comment]
This address has been implemented and is available right now.

Could you please check this endpoint at [http://localhost:8000/docs](http://localhost:8000/docs) and make a call to this endpoint from there? Also, please check [http://localhost:8000/WebAI](http://localhost:8000/WebAI).

Could you provide more information, such as your operating system?
