### ISSUE TITLE
how we can use this end points in custom chatbots in tuts or guides ??

### ISSUE THREAD

**Issue by Arifsha40** [Amm1rr/WebAI-to-API#4]
how we can use this end points in custom chatbots in tuts or guides ??

**Comment by Amm1rr** [comment]
## Accessing the Endpoints in Custom Chatbots

Using the endpoints in your own chatbot projects is straightforward. The [examples](https://github.com/Amm1rr/WebAI-to-API/tree/master/examples) folder contains sample code demonstrating how to call the API. 

For instance:

- [example_bard.py](https://github.com/Amm1rr/WebAI-to-API/blob/master/examples/example_bard.py) 
- [example_chatgpt1.py](https://github.com/Amm1rr/WebAI-to-API/blob/master/examples/example_chatgpt1.py)
- [example_chatgpt2.py](https://github.com/Amm1rr/WebAI-to-API/blob/master/examples/example_chatgpt2.py)
- [example_claude.py](https://github.com/Amm1rr/WebAI-to-API/blob/master/examples/example_claude.py)

The endpoints work just like any standard JSON API. You simply make HTTP requests with JSON payloads.

You can also refer to the OpenAI documentation for the [v1/chat/completions](https://platform.openai.com/docs/api-reference/chat/create) endpoint. 

For other projects like [Auto Code Review](https://github.com/Amm1rr/Auto-Code-Review/) or [ShellGPT](https://github.com/TheR1D/shell_gpt/), you just need to update the host address in the configuration.

Let me know if you have any other questions!

**Comment by Arifsha40** [comment]
ok thx for the reply really appreciate it. i will try it out -- 

what I meant is that can we use this project's custom endpoints in bettergpt.chat  like chatbots ui's?   if yes then what we can use as API ?

**Comment by Amm1rr** [comment]
Yeah sure, it's possible, it's the main goal of this project.

- So I haven't actually used [Better ChatGPT](https://github.com/Anthropic/better-chatgpt) myself, but I checked out their source code, and I don't see an obvious way to configure it to use a custom endpoint.
- They're using frontend endpoints to hit the OpenAI API. If they were using the `v1/chat/completions` model, you could totally plug in `WebAI` without changing any code.

- By the way to make `Better ChatGPT` compatible with `WebAI` just needs a small change in **Better ChatGPT** [**api.py**](https://github.com/ztjhz/BetterChatGPT/blob/34773212eafd9f93a1285fb8a185e8a4a412c89c/src/api/api.ts) file
    
    There needs a small change for function `getChatCompletion` in file [**line 50**](https://github.com/ztjhz/BetterChatGPT/blob/34773212eafd9f93a1285fb8a185e8a4a412c89c/src/api/api.ts#L50) to **line 89** to use WebAI endpoint:
        `http://localhost:8000/v1/chat/completions`

It's simple and should not be too difficult.
