### ISSUE TITLE
Change Claude to ChatGPT endpoint

### ISSUE THREAD

**Issue by johnd0e** [Amm1rr/WebAI-to-API#6]
`http://127.0.0.1:8000/claude/v1/chat/completions` would be much more compatible with most existing tools, because it's very rare when a tool has possibility to customize particular endpoint.
Usually it is possible to enter custom api base, like `http://127.0.0.1:8000/claude/v1`

P.S
Still, some tools expect that api base will by in the root, and allow to customize only host.

**Comment by Amm1rr** [comment]
You've made a solid observation, thank you. I'll take that into consideration and make the necessary adjustments. 
I'll make sure to implement the changes accordingly.
Cheers!

**Comment by johnd0e** [comment]
1. https://github.com/Amm1rr/WebAI-to-API/commit/1a755bdb113fbfa99310380d90c38fcf0508e975#r125280001
2. But even after the fix my request leads to `Error : __enter__`

**Comment by Amm1rr** [comment]
Do you have still problem with that?

**Comment by johnd0e** [comment]
Branch `stream` we are testing in another issue, so I have checked on `master`.
With `"stream": "true"` it waits several seconds, and then `Error : __enter__`
